### ISSUE TITLE
About camvid

### ISSUE THREAD

**Issue by xiaodaomingye459** [ydhongHIT/DDRNet#25]
Hello, I noticed that the prediction result of your paper in the Camvid data set is marked with black ignore label. May I ask how you did it? If my prediction result only has 11 categories, there will be no such effect.

**Comment by xiaodaomingye459** [comment]
Here is the prediction result，there are only 11 categories, what can I do to get the prediction like yours.
![image](https://user-images.githubusercontent.com/83204995/168746460-4b0bd068-fe98-4bc0-a0d3-2b6e8fd35683.png)
Maybe I don't know much about it，whether you can publish your dataset of camvid.
My email is 755435459@qq.com
Thank you very much indeed.

**Comment by ydhongHIT** [comment]
> Here is the prediction result，there are only 11 categories, what can I do to get the prediction like yours. ![image](https://user-images.githubusercontent.com/83204995/168746460-4b0bd068-fe98-4bc0-a0d3-2b6e8fd35683.png) Maybe I don't know much about it，whether you can publish your dataset of camvid. My email is [755435459@qq.com](mailto:755435459@qq.com) Thank you very much indeed.

The original CamVid consists of 32 classes. This is because during training, I ingored the other 21 classes instead of merging the 32 classes into 11 classes. So when getting the mIoU, I follow the same strategy. And if you want to get the visualized results with only 11 classes, you can directly visualized the network output without considering the ignored pixels. The dataset I used is provided in the readme, the same as the PP-Liteseg. I hope this can help you.
